# This file was generated by the s3ti release workflow. DO NOT EDIT.
cask "s3ti" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "b35e3716e1e8af0a2857b52b7a24e471713bc6287a3e12d642611bc71c2f8936"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4c362c2e71b64b7a0cac516eb3f711ed55062796a5ee290b0ba23f44885ea83c"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8278a7023b9cf61ec6ce83d69a75776dfcb66a48b6aad0a7eaa5edd321dca9f3"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "54fc2fb63d2910eee235ecdebbd480ff6772ad23d0b10a374cdb805dcf0bcf33"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_linux_arm64.tar.gz"
    end
  end

  name "s3ti"
  desc "Terminal browser for S3, public and private buckets alike"
  homepage "https://github.com/arksigma/s3ti"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s3ti"

  # No zap stanza required
end
