# This file was generated by the s3ti release workflow. DO NOT EDIT.
cask "s3ti" do
  version "0.13.1"

  on_macos do
    on_intel do
      sha256 "9a708c28faa5e88f2f3bf3d3d821058310415b24058ad0ff6140eb6b585311bd"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8a32746a7aa638f4541804ec22f371d64994235242df073b7cc1421d71829077"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7de4e53fe73730b37bd4a53015662ffc12971ac3cc56a83692f30b4d2eb6fe0a"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d28072c774e7df4c4b10aa1bf735bb89b69164747ee759aac7cbd86fccb18b83"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_linux_arm64.tar.gz"
    end
  end

  name "s3ti"
  desc "Terminal browser for S3, public and private buckets alike"
  homepage "https://github.com/arksigma/s3ti"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s3ti"

  # No zap stanza required
end
