# This file was generated by the s3ti release workflow. DO NOT EDIT.
cask "s3ti" do
  version "0.12.1"

  on_macos do
    on_intel do
      sha256 "a1192341e0c061a70ff8431e2664f20eec069f4b86ce94e51de4aa444d6de7e5"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bbd4e6b05e37f3caa858896cd98a1104502805f2f9033aeb368c4de943c57fe3"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e99f3430a0c254a728bd280d0863d6b5e27de51c0ee401e853394a2f35611df7"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "45c008b4b8e29fae134a3c0ebfa90ad6e2a8e4edc4eb9b3f8d1da7d0ece62770"
      url "https://github.com/arksigma/s3ti-dist/releases/download/v#{version}/s3ti_#{version}_linux_arm64.tar.gz"
    end
  end

  name "s3ti"
  desc "Terminal browser for S3, public and private buckets alike"
  homepage "https://github.com/arksigma/s3ti"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s3ti"

  # No zap stanza required
end
