# This file was generated by GoReleaser. DO NOT EDIT.
cask "tofurkey" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6c272a4b52d59e0e14d3fcced9184191ffa02659bee088a08a17e4560833d10f"
      url "https://github.com/arksigma/tofurkey/releases/download/v#{version}/tofurkey_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cb160b6c6fd4b32d96b7ab4301a699ceaf08f0850e4298ad05ae0c385af48ec2"
      url "https://github.com/arksigma/tofurkey/releases/download/v#{version}/tofurkey_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0609ba2dd3e46ad841119f6250d33283fcc8a4e27f67e0fcea388a02d6ca75a"
      url "https://github.com/arksigma/tofurkey/releases/download/v#{version}/tofurkey_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f6d6c7597ee3c780e64c933961f98fc0e93eeab8d56d2689bd0a41c3662cd9ca"
      url "https://github.com/arksigma/tofurkey/releases/download/v#{version}/tofurkey_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tofurkey"
  desc "TUI for browsing and operating on terraform/opentofu workspaces"
  homepage "https://github.com/arksigma/tofurkey"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tofurkey"

  # No zap stanza required

  caveats <<~EOS
    tofurkey shells out to terraform or opentofu — install one before use:
      brew install opentofu
  EOS
end
