# This file was generated by GoReleaser. DO NOT EDIT.
cask "tofurkey" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2fc1e66d69e2f1d00c75870b87e28989b22d88ae24e07240c91faef41d5ba491"
      url "https://github.com/arksigma/tofurkey-dist/releases/download/v#{version}/tofurkey_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1492ba603097cf54d35e4ea73831f0b0bdfc7b4c82a3a39e7ea4ca01183a543b"
      url "https://github.com/arksigma/tofurkey-dist/releases/download/v#{version}/tofurkey_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eebb294a5d798b4d324f574ae99ca00c237929fedab511512282fc70371385e8"
      url "https://github.com/arksigma/tofurkey-dist/releases/download/v#{version}/tofurkey_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f3453814a3f6aa24a1666cb3ed8852d60a290312ff7576a34f92fc7a1f2615b7"
      url "https://github.com/arksigma/tofurkey-dist/releases/download/v#{version}/tofurkey_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tofurkey"
  desc "TUI for browsing and operating on terraform/opentofu workspaces"
  homepage "https://github.com/arksigma/tofurkey"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tofurkey"

  # No zap stanza required

  caveats <<~EOS
    tofurkey shells out to terraform or opentofu — install one before use:
      brew install opentofu
  EOS
end
