# This file was generated by GoReleaser. DO NOT EDIT.
cask "tofurkey" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "20d462a47b7cf0478d9b5c56f6b199f3a1e691dfede124c1f3d013e0ca19e0de"
      url "https://github.com/arksigma/tofurkey-dist/releases/download/v#{version}/tofurkey_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3614264d11d134339c0c0c585b4628238c13edd58ed906e316646bcdb325db82"
      url "https://github.com/arksigma/tofurkey-dist/releases/download/v#{version}/tofurkey_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a1af0aeaf6fb23f1888b2847c4fe6579d18a902ae05cabeca6baff29387bebd9"
      url "https://github.com/arksigma/tofurkey-dist/releases/download/v#{version}/tofurkey_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b39c4708d06132c67a9d8cfe8ab0947c766ebf4098a22aff1dd6c63ba7fbce47"
      url "https://github.com/arksigma/tofurkey-dist/releases/download/v#{version}/tofurkey_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tofurkey"
  desc "TUI for browsing and operating on terraform/opentofu workspaces"
  homepage "https://github.com/arksigma/tofurkey"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tofurkey"

  # No zap stanza required

  caveats <<~EOS
    tofurkey shells out to terraform or opentofu — install one before use:
      brew install opentofu
  EOS
end
